### ISSUE TITLE
run polkadot-launch config.json error

### ISSUE THREAD

**Issue by zhangtianai** [shawntabrizi/polkadot-launch#6]
```
 ~ polkadot-launch config.json
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/Users/xietingfeng/config.json'
Require stack:
- /usr/local/lib/node_modules/polkadot-launch/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/polkadot-launch/dist/index.js:38:14)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/polkadot-launch/dist/index.js' ]
}

```

**Comment by shawntabrizi** [comment]
Did you create a `config.json` file?
